CFLAGS = -Wall
CFLAGS += -Werror
CFLAGS += -Wextra
CFLAGS += -pedantic
CFLAGS += -pedantic-errors
CFLAGS += -std=c11
CFLAGS += -ggdb

../build/day1_p1: day1_p1.c
	$(CC) -o $@ $^ $(CFLAGS)

../build/day1_p2: day1_p2.c
	$(CC) -o $@ $^ $(CFLAGS)
