CFLAGS = -Wall
CFLAGS += -Werror
CFLAGS += -Wextra
CFLAGS += -pedantic
CFLAGS += -pedantic-errors
CFLAGS += -std=c++11
CFLAGS += -ggdb

../build/day4_p1: day4_p1.c
	$(CXX) -o $@ $^ $(CFLAGS)

../build/day4_p2: day4_p2.c
	$(CXX) -o $@ $^ $(CFLAGS)
